log_dir: "Models/JSUT"
first_stage_path: "first_stage.pth" # path to the last checkpoint of the 1st stage (it will be used as the initial model for the 2nd stage)
save_freq: 1
log_interval: 20
device: "cuda"
multigpu: false
epochs_1st: 201 # number of epochs for first stage training
epochs_2nd: 101 # number of peochs for second stage training
batch_size: 12
pretrained_model: "Models/JSUT/epoch_2nd_00098.pth" # pre-trained model for the current stage
second_stage_load_pretrained: true # set to true if the pre-trained model is for 2nd stage (if false, the pre-trained model path will be ignored)
load_only_params: false # set to true if do not want to load epoch numbers and optimizer parameters

train_data: "Data/train_list.txt"
val_data: "Data/val_list.txt"

F0_path: "Utils/JDC/jsut_500e.pth"
ASR_config: "Utils/ASR/config.yml"
ASR_path: "Utils/ASR/jsut_1000e.pth"

preprocess_params:
  sr: 24000
  spect_params:
    n_fft: 2048
    win_length: 1200
    hop_length: 300

model_params:
  hidden_dim: 512
  n_token: 80
  style_dim: 128
  n_layer: 3
  dim_in: 64
  max_conv_dim: 512
  n_mels: 80
  dropout: 0.2

loss_params:
    lambda_mel: 5. # mel reconstruction loss (1st & 2nd stage)
    lambda_adv: 1. # adversarial loss (1st & 2nd stage)
    lambda_reg: 1. # adversarial regularization loss (1st & 2nd stage)
    lambda_fm: 0.1 # feature matching loss (1st & 2nd stage)
    
    lambda_mono: 1. # monotonic alignment loss (1st stage, TMA)
    lambda_s2s: 1. # sequence-to-sequence loss (1st stage, TMA)
    TMA_epoch: 20 # TMA starting epoch (1st stage)

    # https://github.com/yl4579/StyleTTS/issues/7
    TMA_CEloss: false # whether to use cross-entropy (CE) loss for TMA

    lambda_F0: 1. # F0 reconstruction loss (2nd stage)
    lambda_norm: 1. # norm reconstruction loss (2nd stage)
    lambda_dur: 1. # duration loss (2nd stage)

optimizer_params:
  lr: 0.0001
